import type { Metadata } from "next";
import { storyblokInit, apiPlugin } from "@storyblok/react/rsc";

import Header from "./components/Header/Header";
import Footer from "./components/Footer/Footer";

import { StoryblokProvider } from "app/components/StoryblokProvider";
import "./globals.scss";

export const metadata: Metadata = {
  title: "JCL Coaching",
  description: "Generated by create next app",
};

const cachedFetch = (input: any, init?: any): Promise<Response> => {
  return fetch(input, {
    ...init,
    cache: process.env.NODE_ENV === "development" ? "no-store" : "force-cache",
  });
};

storyblokInit({
  accessToken: process.env.STORYBLOK_TOKEN,
  use: [apiPlugin],
  apiOptions: {
    fetch: cachedFetch,
  },
});

export default function RootLayout({
  children,
  params: { lang },
}: {
  children: React.ReactNode;
  params: { lang: string };
}) {
  return (
    <StoryblokProvider>
      <html lang={lang}>
        <body>
          <Header locale={lang} />
          {children}
          <Footer lang={lang} />
        </body>
      </html>
    </StoryblokProvider>
  );
}